on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - 'master'

name: Build Compadre and Padrino World Maps

jobs:
  render:
    name: Build Demography Maps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
      - name: Install package dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://cloud.r-project.org/')"
          Rscript -e "remotes::install_deps(repos = 'https://cloud.r-project.org/')"
      - name: Pull and Plot Data
        run: |-
          Rscript plot_compadrino.R
      - name: commit Results
        run: |-
          git config user.name ${{github.actor}}
          git config user.email ${{github.actor}}
          git add figures
          git commit -m 'update figures [ci skip]' || echo "No changes"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{github.ref}} || echo "No changes"
